spring:
  application:
    name: client-service

server:
  port: ${PORT:8081}

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, shutdown
  endpoint:
    shutdown:
      enabled: true
